"""Fill in a module description here. blah."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_meins.ipynb.

# %% auto 0
__all__ = ['say_hello', 'foo']

# %% ../nbs/01_meins.ipynb 2
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# %% ../nbs/01_meins.ipynb 4
def foo(): pass
